CREATE OR REPLACE TABLE CANDIDATE_ANALYTICS (
    AUTH_ID INT,
    CANDIDATE_NAME STRING,
    SCORE_RAW FLOAT,      
    DATE_CAPTURED DATE,    
    HIRING_STATUS STRING
);

SELECT * FROM CANDIDATE_ANALYTICS;

